# Generated by Django 4.1.2 on 2022-10-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock', models.IntegerField(verbose_name='Stock')),
                ('description', models.TextField(max_length=200, verbose_name='Descripcion')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products', verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('doc', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Numero de documento')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de usuario')),
                ('email', models.CharField(blank=True, max_length=60, null=True, verbose_name='Email')),
                ('user_active', models.BooleanField(default=True)),
                ('user_type', models.CharField(max_length=1, verbose_name='Tipo usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
