# Generated by Django 3.2.1 on 2023-01-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GlobalApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table=None,
        ),
    ]
