# Generated by Django 4.1.3 on 2022-11-03 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GlobalApi', '0002_products_available_alter_products_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_client', models.CharField(max_length=50)),
                ('last_name_client', models.CharField(max_length=100)),
                ('email_client', models.EmailField(max_length=254)),
                ('doc_client', models.ForeignKey(db_column='doc', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_address', models.CharField(max_length=300, verbose_name='Order Address')),
                ('order_date', models.DateField(null=True)),
                ('order_active', models.BooleanField(default=True)),
                ('order_client_doc', models.ForeignKey(db_column='doc_client', on_delete=django.db.models.deletion.CASCADE, to='GlobalApi.client')),
                ('order_client_lastname', models.ForeignKey(db_column='last_name_client', on_delete=django.db.models.deletion.CASCADE, related_name='client_lastname_order', to='GlobalApi.client')),
                ('order_client_name', models.ForeignKey(db_column='name_client', on_delete=django.db.models.deletion.CASCADE, related_name='client_name_order', to='GlobalApi.client')),
                ('order_product', models.ManyToManyField(to='GlobalApi.products')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name_admin', models.CharField(max_length=50)),
                ('last_name_admin', models.CharField(max_length=100)),
                ('email_admin', models.EmailField(max_length=254)),
                ('doc_admin', models.ForeignKey(db_column='doc', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
