# Generated by Django 4.1.3 on 2022-11-04 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GlobalApi', '0003_client_order_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_client_doc',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_client_lastname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_client_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_product',
        ),
        migrations.AddField(
            model_name='order',
            name='order_client_id',
            field=models.ForeignKey(db_column='id_client', default='A', on_delete=django.db.models.deletion.CASCADE, to='GlobalApi.client'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id_admin',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_client',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ProductUnits',
            fields=[
                ('product_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_unit_state', models.CharField(max_length=10)),
                ('product_id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to='GlobalApi.products')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_product_units',
            field=models.ManyToManyField(to='GlobalApi.productunits'),
        ),
    ]
