# Generated by Django 4.1.3 on 2022-11-04 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GlobalApi', '0004_remove_order_order_client_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_client_id',
            field=models.ForeignKey(db_column='id_client', default=0, on_delete=django.db.models.deletion.CASCADE, to='GlobalApi.client'),
        ),
    ]
