# Generated by Django 3.2.1 on 2023-01-19 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GlobalApi', '0004_auto_20230119_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_products',
            new_name='order_product_units',
        ),
    ]
