# Generated by Django 3.2.1 on 2023-01-30 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GlobalApi', '0006_alter_order_order_product_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
